# Generated by Django 6.0.3 on 2026-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
