# Generated by Django 6.0.3 on 2026-04-18 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicalfile_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_files', to='core.doctor'),
        ),
    ]
