# Generated by Django 6.0.4 on 2026-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicalfile_last_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ordonnance', 'Ordonnance'), ('resultat_labo', 'Résultat de labo'), ('resultat_efr', 'Résultat EFR'), ('endoscopie', 'Compte-rendu endoscopie'), ('radiologie', 'Imagerie radiologique'), ('sortie', 'Compte-rendu de sortie'), ('vaccination', 'Carnet de vaccination')], max_length=100),
        ),
    ]
