# Generated by Django 6.0.3 on 2026-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicalfile_last_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('doctor', 'Doctors'), ('guardian', 'Guardians'), ('admin', 'Admins')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
