# Generated by Django 6.0.4 on 2026-04-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('doctor', 'Doctors'), ('guardian', 'Guardians'), ('admin', 'Admins')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
