# Generated by Django 6.0.3 on 2026-04-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vaccinationrecord_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalfile',
            name='is_shared',
        ),
    ]
