# Generated by Django 6.0.4 on 2026-04-30 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement_target_audience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalfile',
            name='is_shared',
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='guardian',
            field=models.ForeignKey(limit_choices_to={'role': 'guardian'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
