# Generated by Django 6.0.4 on 2026-05-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='models_name',
            new_name='model_name',
        ),
    ]
